src/main/java/cuchaz/enigma/CommandMain.java, src/main/java/cuchaz/enigma/Deobfuscator.java, src/main/java/cuchaz/enigma/Main.java, src/main/java/cuchaz/enigma/bytecode/accessors/ConstInfoAccessor.java, src/main/java/cuchaz/enigma/gui/Gui.java, src/main/java/cuchaz/enigma/gui/GuiController.java, src/main/java/cuchaz/enigma/gui/elements/MenuBar.java, src/main/java/cuchaz/enigma/gui/filechooser/FileChooserAny.java, src/main/java/cuchaz/enigma/mapping/Mappings.java, src/main/java/cuchaz/enigma/mapping/MappingsEnigmaReader.java, src/main/java/cuchaz/enigma/mapping/MappingsEnigmaWriter.java, src/main/java/cuchaz/enigma/mapping/MappingsJsonReader.java, src/main/java/cuchaz/enigma/mapping/MappingsJsonWriter.java, src/main/java/cuchaz/enigma/mapping/MappingsSRGWriter.java, src/test/java/cuchaz/enigma/TestTranslator.java
Others changes:
~ Rework File menu
~ Force UTF-8 for all I/O operations
~ Enigma now detect the original file format and use the correct one when you save a mapping
=> Implement Enigma directory format

src/main/java/cuchaz/enigma/bytecode/LocalVariableRenamer.java
Improves visual grepping for any arguments greatly, works well with game objects as well as java primitives.
=> Change method param default naming scheme (#42)

src/main/java/cuchaz/enigma/mapping/ClassMapping.java, src/main/java/cuchaz/enigma/mapping/Mappings.java, src/main/java/cuchaz/enigma/mapping/MappingsEnigmaReader.java, src/main/java/cuchaz/enigma/mapping/MappingsEnigmaWriter.java
This is the rework of the saving system. I don't merge it to the master until I'm not totally sure that everything is working properly.
=> Rework saving system to improve saving time (#35)

src/main/java/cuchaz/enigma/bytecode/translators/TranslationAnnotationVisitor.java
=> Fix annotation npe for villager

src/main/java/cuchaz/enigma/analysis/MethodInheritanceTreeNode.java, src/main/java/cuchaz/enigma/gui/Gui.java, src/main/java/cuchaz/enigma/gui/MethodTreeCellRenderer.java
=> Adds a red highlight for overridden methods in method inheritance tree gui

src/main/java/cuchaz/enigma/gui/Gui.java, src/main/java/cuchaz/enigma/gui/MethodTreeCellRenderer.java, src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
Now inheritance tree bleak color no longer affects other trees
Also add a github link
=> Few minor render tweaks

build.gradle, gradle/wrapper/gradle-wrapper.properties
https://discordapp.com/channels/507304429255393322/521545796882006027/576330380584419338
And update gradle to latest 5.4.1
=> Use our procyon to fix compiler issues

src/main/java/cuchaz/enigma/gui/Gui.java, src/main/java/cuchaz/enigma/gui/GuiController.java, src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java, src/main/java/cuchaz/enigma/gui/elements/PopupMenuBar.java, src/main/java/cuchaz/enigma/gui/panels/PanelDeobf.java, src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java, src/main/java/cuchaz/enigma/gui/panels/PanelObf.java, src/main/java/cuchaz/enigma/gui/util/History.java
Adds "Go back" and "Go forward" in the right click context menu (PopupMenuBar) (replacing "Go to previous") and allows navigating with mouse button 4 and 5.
In addition, I have attempted to move some of the related Controller logic (borrowing from MVC) from Gui to GuiController.
=> Add forward and backward reference history with mouse navigation

src/main/java/cuchaz/enigma/Enigma.java, src/main/java/cuchaz/enigma/EnigmaProfile.java, src/main/java/cuchaz/enigma/EnigmaProject.java, src/main/java/cuchaz/enigma/EnigmaServices.java, src/main/java/cuchaz/enigma/Main.java, src/main/java/cuchaz/enigma/ProposingTranslator.java, src/main/java/cuchaz/enigma/analysis/BuiltinPlugin.java, src/main/java/cuchaz/enigma/gui/DecompiledClassSource.java, src/main/java/cuchaz/enigma/gui/Gui.java, src/main/java/cuchaz/enigma/gui/GuiController.java, src/main/resources/META-INF/services/cuchaz.enigma.api.EnigmaPlugin, src/main/resources/profile.json
This is in case we move some name suggestions, like enum name suggestions and bridge name suggestions to enigma itself, we can allow them to coexist with the suggestion from stitch.
=> Allow multiple services for enigma

src/main/java/cuchaz/enigma/analysis/SourceIndex.java, src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
=> Tweak runemoro's stats generator to be compatible with multiple services

src/main/java/cuchaz/enigma/translation/mapping/serde/EnigmaMappingsReader.java, src/test/java/cuchaz/enigma/mapping/TestComments.java, src/test/resources/comments/test.mapping
Previously any words other than the first one in a line were getting cut out.
=> Fix comments

build.gradle, src/main/java/cuchaz/enigma/EnigmaProject.java, src/main/java/cuchaz/enigma/analysis/BuiltinPlugin.java, src/main/java/cuchaz/enigma/analysis/ClassCache.java, src/main/java/cuchaz/enigma/analysis/IndexSimpleVerifier.java, src/main/java/cuchaz/enigma/analysis/InterpreterPair.java, src/main/java/cuchaz/enigma/analysis/index/JarIndex.java, src/main/java/cuchaz/enigma/bytecode/translators/TranslationSignatureVisitor.java, src/main/java/cuchaz/enigma/gui/GuiController.java, src/main/java/cuchaz/enigma/utils/Utils.java, src/test/resources/proguard-build.conf, src/test/resources/proguard-test.conf
=> Support java 9+ and gradle 6+

src/main/java/cuchaz/enigma/gui/dialog/CrashDialog.java, src/main/resources/lang/en_us.json, src/main/resources/lang/fr_fr.json
=> Added export functionality to CrashDialog.java

src/main/java/cuchaz/enigma/gui/elements/PopupMenuBar.java, src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java, src/main/resources/lang/en_us.json, src/main/resources/lang/fr_fr.json
=> Added zoom for PanelEditor

README.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java, src/main/java/cuchaz/enigma/translation/mapping/NameValidator.java, src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
- Update Gradle to 6.3, and replace deprecated features
- Allow renaming classes to no package (closes https://github.com/FabricMC/Enigma/issues/215)
- Fix issue with CFR (closes https://github.com/FabricMC/Enigma/issues/207)
=> Fix a few bugs

build.gradle
Downstream doesn't take a half-done darcula without a groupId
=> Fix darcula dependency

src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java, src/main/java/cuchaz/enigma/utils/search/SearchUtil.java
Fixes the search dialog locking up sometimes when typing in search queries by making search asynchronous.
=> Async search

build.gradle, src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
Just to ease javadoc writing.
Here's how it looks:
=> Add tags to javadoc dialog

enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaSyntaxKit.java
=> Fix editor contents being changeable through certain key combinations

enigma-cli/src/main/java/cuchaz/enigma/command/DecompileCommand.java
Has been broken for a few months, thought I'd want to update now 👀
Fixes #243
=> Fix decompile command

enigma-cli/build.gradle, enigma-server/build.gradle, enigma-swing/build.gradle, gradle/wrapper/gradle-wrapper.properties
e.g. `./gradlew enigma-swing:run`
=> Add gradle run tasks

enigma/build.gradle, enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java, enigma/src/main/java/cuchaz/enigma/translation/representation/AccessFlags.java, enigma/src/test/java/cuchaz/enigma/TestAllowableClashes.java, enigma/src/test/java/cuchaz/enigma/ValidationContextMatcher.java, enigma/src/test/java/cuchaz/enigma/inputs/visibility/ClassA.java, enigma/src/test/java/cuchaz/enigma/inputs/visibility/ClassB.java
Made some improvements to MappingValidator to take access levels into account when checking name uniqueness.
Should hopefully fix #191 and fix #246 
Also added a Test to ensure this doesn't get broken, etc.
=> Validation improvements

build.gradle, enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java, enigma-swing/src/main/java/cuchaz/enigma/gui/elements/DeobfPanelPopupMenu.java, enigma/src/main/resources/lang/en_us.json, enigma/src/main/resources/lang/fr_fr.json
=> Add popup menu to deobf panel to quickly rename a package/class

enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java, enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
=> Fix right panel width being reset on ui update

enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java, enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java, enigma/src/main/resources/lang/en_us.json, enigma/src/main/resources/lang/fr_fr.json
Not revolutionary, but can be very useful when doing unpick definitions manually
=> Copy method/field descriptor on click

enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaSyntaxKit.java
They now have the default color
Closes #374
=> Fix warning/error formatting in editor

enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
This method allows users to read multiple mapping files that may not be in the same directory, or just specific mapping files from a directory.
My use case for this: incremental mapping style checking in Filament's `JavadocLintTask` currently requires me to [copy the files into a temp directory](https://github.com/FabricMC/fabric-filament/blob/99aecd1aff1ff03129f6e7e2c3b807df9f835142/src/main/java/net/fabricmc/filament/task/JavadocLintTask.java#L62) and then parse the mappings, or parse each file into its own `EntryTree` and merge them. This should most likely be faster and more convenient than either approach.
I also had to make all of the parser methods static for this :smile:
=> Add EnigmaMappingsReader.readFiles

enigma/build.gradle, enigma/src/main/java/cuchaz/enigma/source/cfr/CfrDecompiler.java, enigma/src/main/java/cuchaz/enigma/source/cfr/CfrSource.java, enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
fixes #368 context for token references, missing some field and method references
depends on https://github.com/FabricMC/cfr/pull/6
=> Update cfr and fixes a few related issues

enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java, enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java, enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
=> Makes sure save mappings is completed before next action

.github/workflows/build.yml, .github/workflows/release.yml, build.gradle, enigma-swing/build.gradle, enigma/build.gradle, gradle/wrapper/gradle-wrapper.properties
Update's deps and fixes build on JDK 17. Still targets JDK 16 for now, there isnt much benefit to target 17, but likewise not much reason to stick with 16, can give it a little bit more time before making the jump 👍
=> Update deps & Java 17

enigma-swing/src/main/java/cuchaz/enigma/gui/config/Decompiler.java, enigma/src/main/java/cuchaz/enigma/analysis/BuiltinPlugin.java, enigma/src/main/java/cuchaz/enigma/source/Decompilers.java, enigma/src/main/java/cuchaz/enigma/source/bytecode/BytecodeDecompiler.java, enigma/src/main/java/cuchaz/enigma/source/bytecode/BytecodeSource.java, enigma/src/main/java/cuchaz/enigma/source/bytecode/EngimaTextifier.java, enigma/src/main/java/cuchaz/enigma/source/bytecode/EnigmaTextifier.java
Currently readonly, shouldnt be too hard to add the declaration's at a later date.
=> Add basic bytecode view.

enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java
For a better build error for https://github.com/FabricMC/yarn/pull/2756#discussion_r729958012
=> Add a check for space indentation

enigma-swing/build.gradle
Hi @modmuss50 !
I did some improvements to the fontchooser. It's time to update. 😉 
Best regards
Daniel
=> Bump fontchooser to 2.5.2

enigma-cli/src/main/java/cuchaz/enigma/command/MapSpecializedMethodsCommand.java
See issue here: https://discord.com/channels/507304429255393322/592749519171616796/1018282750400274542
Full testing needed when its not late, but seems correct.
=> Ensure the root method is used when mapping specialized methods

enigma-swing/src/main/java/cuchaz/enigma/gui/ClassSelector.java, enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java, enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java, enigma-swing/src/main/java/cuchaz/enigma/gui/NestedPackages.java, enigma-swing/src/main/java/cuchaz/enigma/gui/node/ClassSelectorPackageNode.java, enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
=> Nested packages in Swing UI

enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/StatsDialog.java, enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java, enigma/src/main/resources/lang/en_us.json
Taken from https://github.com/QuiltMC/enigma/commit/a1892c0f3f08b3b19fac700618a44d6789402844.
=> Allow filtering of packages in Mapping Stats window

enigma-swing/src/main/java/cuchaz/enigma/gui/elements/EditorPopupMenu.java, enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java, enigma/src/main/resources/lang/en_us.json
Taken and adapted from https://github.com/QuiltMC/enigma/commit/a746178da0eaf2976faccc9b2f94e127b39baee3.
Closes https://github.com/FabricMC/Enigma/issues/333.
=> Allow pasting directly on renamable tokens

enigma-swing/src/main/java/cuchaz/enigma/gui/panels/IdentifierPanel.java
=> Make all identifier panel entries copyable

enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
Taken from https://github.com/QuiltMC/enigma/commit/681752b8c7f02d4086a6aa88dc9fe5df050f93c8.
=> Clear Javadoc when text is empty

enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
Taken from https://github.com/QuiltMC/enigma/commit/99801f81424f7ef240ecda3ea8a4138434dabf7f.
=> Don't save empty classes

enigma-cli/src/main/java/cuchaz/enigma/command/Main.java, enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndex.java, enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingParseException.java, enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsReader.java, enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/proguard/ProguardMappingsReader.java, enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tiny/TinyMappingsReader.java, enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Reader.java
Extracted from https://github.com/QuiltMC/enigma/commit/bad1042912d31a00a455c5e7931c95b68e7307b4.
=> Improve error handling in some places

enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java, enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java, enigma/src/main/java/cuchaz/enigma/translation/representation/entry/Entry.java, enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldEntry.java, enigma/src/main/java/cuchaz/enigma/translation/representation/entry/LocalVariableEntry.java, enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodEntry.java, enigma/src/main/java/cuchaz/enigma/utils/validation/Message.java, enigma/src/main/resources/lang/en_us.json
Taken and adapted from https://github.com/QuiltMC/enigma/commit/bc04a4d15453e9df1c2068f7043e5e6d3b4f69eb, https://github.com/QuiltMC/enigma/commit/956bc449669a1610f9fee02a3df2069220d8cb5c and https://github.com/QuiltMC/enigma/commit/5a1df24807f86e7d56d7468ed9f3083a2c9eb3e8.
=> Allow shadowing fields

enigma/build.gradle, enigma/src/main/java/cuchaz/enigma/source/procyon/transformers/DropVarModifiersAstTransform.java, enigma/src/main/java/cuchaz/enigma/source/procyon/transformers/ObfuscatedEnumSwitchRewriterTransform.java
Updates CFR to 0.2.1 and Procyon to the latest upstream release, 0.6.0.
=> Update Procyon and CFR

enigma-swing/src/main/java/cuchaz/enigma/gui/elements/AbstractInheritanceTree.java, enigma/src/main/java/cuchaz/enigma/analysis/ClassImplementationsTreeNode.java, enigma/src/main/java/cuchaz/enigma/analysis/ClassInheritanceTreeNode.java, enigma/src/main/java/cuchaz/enigma/analysis/ClassTreeNode.java, enigma/src/main/java/cuchaz/enigma/analysis/MethodImplementationsTreeNode.java, enigma/src/main/java/cuchaz/enigma/analysis/MethodInheritanceTreeNode.java, enigma/src/main/java/cuchaz/enigma/analysis/MethodTreeNode.java
=> Fix double clicking an entry in the "implementations" window not navigating to the respective class/method

enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingValidator.java
=> Fix mapping uniqueness validator always erroring in certain scenarios

enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java, enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java, enigma-swing/src/main/java/cuchaz/enigma/gui/search/SearchUtil.java, enigma/src/main/resources/lang/en_us.json
Small PR to fix issues and improve search dialogs:
- Made sure exact matches appear at the top of results (closes #392)
- Added an "Only show exact matches" checkbox (which resolves #393)
- Changed the keystroke for searching classes and added ones for other searches (closes #408)
=> Search dialog improvements

enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
Deltas were always discarded, leading to old mapping files not getting deleted etc.
=> Fix Enigma dir writer behaving incorrectly after the first write
