FabricMC/Enigma

- src/main/java/cuchaz/enigma/gui/Gui.java
- src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java
Restores rendering the line numbers ruler in the editor, related to issue #39.
> Fixes execution order for line number ruler

- build.gradle
- src/main/java/cuchaz/enigma/Main.java
- src/main/java/cuchaz/enigma/config/Config.java
- src/main/java/cuchaz/enigma/gui/Gui.java
- src/main/java/cuchaz/enigma/gui/MinecraftSyntaxKit.java
- src/main/java/cuchaz/enigma/gui/highlight/BoxHighlightPainter.java
- src/main/java/cuchaz/enigma/gui/highlight/DeobfuscatedHighlightPainter.java
- src/main/java/cuchaz/enigma/gui/highlight/ObfuscatedHighlightPainter.java
- src/main/java/cuchaz/enigma/gui/highlight/OtherHighlightPainter.java
Allows for things like that ^
The default settings are as before
Questions before merge: 
Where should the config be located? Currently in the working dir.
Should I add some presets like the one pictured above?
Things to do later:
Change the theme of the other gui components to fit in with the style.
> Add support for custom themes

- build.gradle
Since f8223ed5b3cb2f5f60a770804b06750ad94928b1, the about menu doesn't show any versions anymore.
This PR takes care of replacing '@VERSION@' with the correct value.
> Replace all occurences of '@VERSION@' during build

- src/main/java/cuchaz/enigma/translation/mapping/serde/EnigmaMappingsWriter.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/SrgMappingsWriter.java
- src/main/java/cuchaz/enigma/utils/LFPrintWriter.java
Done by changing the `PrintWriter`s in the mapping writer classes to a custom implementation overriding `println()`. Closes #87.
> Standardize mapping line endings to LF

- src/main/java/cuchaz/enigma/config/Config.java
- src/main/java/cuchaz/enigma/config/Themes.java
- src/main/java/cuchaz/enigma/gui/Gui.java
The system one can be GTK theme on some linux systems (which can include dark themes). The default one is whatever was set at the beginning before enigma touched anything. Most likely metal or user-set look and feel.
Screenshot with my GTK theme:
> Add System and None (JVM Default) themes.

- src/main/java/cuchaz/enigma/CompiledSourceTypeLoader.java
- src/main/java/cuchaz/enigma/Deobfuscator.java
- src/main/java/cuchaz/enigma/analysis/index/BridgeMethodIndex.java
- src/main/java/cuchaz/enigma/analysis/index/InheritanceIndex.java
- src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
- src/main/java/cuchaz/enigma/bytecode/translators/SourceFixVisitor.java
- src/main/java/cuchaz/enigma/bytecode/translators/TranslationClassVisitor.java
This PR allows `BridgeMethodIndex` to detect synthetic methods not marked as bridges by performing a series of checks. Additionally, bytecode is now processed to attach the bridge modifier to methods missing it, and fix names such that they match their bridge equivalent.
I am not certain on the validity of them, and how possible it'd be to get false-positives.
> Bridge Method Fixes

- Jenkinsfile
- build.gradle
There's no pretty way to replace tokens in source files with gradle, but I believe this way is at least prettier. It also properly sets up the dependency graph for libJar, which is currently being built incorrectly.
> Improve source generation and fix libJar

- src/main/java/cuchaz/enigma/gui/EnigmaQuickFindDialog.java
- src/main/java/cuchaz/enigma/gui/EnigmaSyntaxKit.java
- src/main/java/cuchaz/enigma/gui/QuickFindAction.java
This PR fixes the quick find dialog to correctly fit within the screen.
Additionally, the dialog will now select all text on open allowing it to be easily replaced, and if any text is highlighted in the editor, it will be set in the find dialog on open
> Quick find fixes

- src/main/java/cuchaz/enigma/gui/Gui.java
- src/main/java/cuchaz/enigma/gui/GuiController.java
- src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java
This PR changes the editor to open the rename dialog as soon as the user starts typing on a nameable token.
However, this does break existing functionality. Hotkeys such as `R` to rename and `N` to navigate can no longer be used as they were before, because it'd be impossible to distinguish these from normal typing. The solution here is to mask them with the control modifier.
Definitely will need opinions from people on these changes before merging.
> Rename in place functionality

- src/main/java/cuchaz/enigma/CommandMain.java
- src/main/java/cuchaz/enigma/analysis/index/EntryIndex.java
- src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
- src/main/java/cuchaz/enigma/analysis/index/PackageVisibilityIndex.java
- src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
This PR introduces an index that partitions classes to identify which classes must exist in the same package, and more thoroughly recreates the functionality of the checkMappings command from Weave. The idea is that the index introduced here can be used in Enigma itself in the future.
In addition, this sets up exit codes and uses the System.err output for errors so we can hopefully use it in scripts.
> checkmappings command

- src/main/java/cuchaz/enigma/analysis/index/IndexReferenceVisitor.java
- src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
- src/main/java/cuchaz/enigma/analysis/index/JarIndexer.java
- src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
- src/main/java/cuchaz/enigma/translation/representation/Lambda.java
- src/main/java/cuchaz/enigma/translation/representation/MethodDescriptor.java
- src/main/java/cuchaz/enigma/translation/representation/entry/ParentedEntry.java
Further investigation shows that a method may call another method with an inaccessible package-private type as a parameter or a return value. Only the owner of the method matters. It is therefore incorrect to assume that a class does not depend on another class being in the same package based on the descriptor of the methods called.
Lambdas create rather special cases that are handled in this PR. It ties in with how LambdaMetaFactory works and the methods implemented in the generated lambda class.
> Method type reference corrections

- src/main/java/cuchaz/enigma/translation/mapping/serde/EnigmaMappingsWriter.java
Should be merged together with https://github.com/sfPlayer1/Matcher/pull/4. Fixes https://github.com/FabricMC/Enigma/issues/147.
Currently, Enigma can read mappings using both unqualified and qualified inner class names (see [here](https://github.com/FabricMC/Enigma/blob/master/src/main/java/cuchaz/enigma/translation/mapping/serde/EnigmaMappingsReader.java#L144) and [here](https://github.com/FabricMC/Enigma/blob/master/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java#L182-L188)), but always saves the qualified name by default. This PR makes Enigma save the unqualified name instead while still being able to read both formats.
The change to intermediaries in yarn seems like a good time to make this change, since obfuscated class names are about to get longer, and …
> Save unqualified inner class names

- src/main/java/cuchaz/enigma/CommandMain.java
- src/main/java/cuchaz/enigma/command/ComposeMappingsCommand.java
- src/main/java/cuchaz/enigma/command/InvertMappingsCommand.java
- src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/TinyMappingsWriter.java
- src/main/java/cuchaz/enigma/utils/Utils.java
The compose command is for remapping the Enigma mappings directory from intermediaries back to Mojang names when building yarn. 
The invert command can be used to create inverted tiny mappings for the initial conversion of yarn mappings to intermediary (since Matcher saving to intermediaries is [currently broken](https://github.com/sfPlayer1/Matcher/issues/5)).
The new convert command now supports writing tiny mappings and can replace weave's tinyify command, fixing https://github.com/FabricMC/weave/issues/2.
Example usage:
- Inverting intermediaries: `invert tiny <intermediaries> tiny:named:official <inverted-intermediaries>`
- Remapping yarn mappings: `compose tiny <(inverted-)intermediaries> enigma <mappings> enigma <remapped-mappings> right` (right means keep mappings on the right …
> Add compose, convert, and invert commands

- src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
I accidentally reversed what the compose command does in my last PR since I was testing it on the wrong file. This fixes that.
> Fix compose translating in wrong direction

- src/main/java/cuchaz/enigma/SourceProvider.java
So Enigma will now display classes as
```java
public class SomeClass {
```
rather than 
```java
public class SomeClass
{
```
(fields and methods already have the brace on the same line).
> Put class opening brace on same line

- src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
When a method owner is an array (for example `[Lnet/minecraft/class_123.clone`), Enigma still creates a `ClassEntry` for the array (see `IndexReferenceVisitor` and `IndexReferenceVisitor`), but translation fails for array classes, which leads to broken code when decompiling. For example, Procyon will add an import statement for the inexistant class.
> Fix array class translation

- src/main/java/cuchaz/enigma/analysis/EntryReference.java
- src/main/java/cuchaz/enigma/analysis/IndexSimpleVerifier.java
- src/main/java/cuchaz/enigma/analysis/InterpreterPair.java
- src/main/java/cuchaz/enigma/analysis/MethodNodeWithAction.java
- src/main/java/cuchaz/enigma/analysis/ReferenceTargetType.java
- src/main/java/cuchaz/enigma/analysis/index/EntryIndex.java
- src/main/java/cuchaz/enigma/analysis/index/IndexReferenceVisitor.java
- src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
- src/main/java/cuchaz/enigma/analysis/index/JarIndexer.java
- src/main/java/cuchaz/enigma/analysis/index/PackageVisibilityIndex.java
- src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
- src/main/java/cuchaz/enigma/translation/representation/AccessFlags.java
Java only allows invoking protected methods and accessing protected fields of objects which are assignable to the calling class. This PR adds information about the target's type to the reference index so that it can be correctly checked when running check-mappings or renaming things in Enigma.
It now detects the issues in https://github.com/FabricMC/yarn/issues/808:
```
ERROR: Must be in one package:
net/minecraft/util/LevelPropagator
net/minecraft/util/LevelPropagator$1
net/minecraft/util/LevelPropagator$2
net/minecraft/world/chunk/light/BlockLightStorage
net/minecraft/world/chunk/light/BlockLightStorage$Data
net/minecraft/world/chunk/light/ChunkBlockLightProvider
net/minecraft/world/chunk/light/ChunkLightProvider
net/minecraft/world/chunk/light/ChunkSkyLightProvider …
```
> Check protected method/field target in visibility index

- src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/RawEntryMapping.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/TinyV2Reader.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/TinyV2Writer.java
- src/test/java/cuchaz/enigma/mapping/TestTinyV2InnerClasses.java
- src/test/java/cuchaz/enigma/mapping/TestV2Main.java
- src/test/resources/tinyV2InnerClasses/c.mapping
- src/test/resources/tinyV2InnerClasses/cuchaz/enigma/Dad.mapping
Partially replaced #146 as requested by @modmuss50 
Needs testing. Code pulled from #146 wholesale
For javadocs, my concern is that a mapping entry is not required for javadoc to be present. Should I move jd to a separate entry tree for saving and loading instead?
> Pulled tinyv2 sl code from jd pr, needs testing

- src/main/java/cuchaz/enigma/bytecode/translators/LocalVariableFixVisitor.java
- src/main/java/cuchaz/enigma/bytecode/translators/TranslationMethodVisitor.java
- src/main/java/cuchaz/enigma/translation/representation/entry/MethodDefEntry.java
A few snapshot ago, Mojang made some changes to the way local variables are obfuscated:
- Rather than setting all LVT names to `☃️`, it now generates a unique name for each source variable (such as`class_2090_1`). Because the parameter table is now valid, it's no longer ignored by the decompiler, which reveals some bugs in `LocalVariableFixVisitor`. These break jar and source export, but not viewing in Enigma since remapping is done after decompilation.
-  The `name` and `ordinal` parameters of enum constructors are no longer marked as synthetic, which causes them to not be removed by Procyon. 
This PR
- Makes `LocalVariableFixVisitor` add `synthetic` flags to the `name` and `ordinal` parameters of enum constructor and set their name to the correct name.
- Makes `LocalVariableFixVisitor` …
> Fix local variable fixer

- src/main/java/cuchaz/enigma/analysis/ClassCache.java
`newFileSystem(Path path, Map<String,?> env)` was added in Java 13, making the call ambiguous.
> Fix compiling on Java 13

- src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java
Can be reproduced when you start typing while your cursor is on the inner class reference token
> Fix inner class renaming

- src/main/java/cuchaz/enigma/CommandMain.java
- src/main/java/cuchaz/enigma/EnigmaProject.java
- src/main/java/cuchaz/enigma/analysis/index/BridgeMethodIndex.java
- src/main/java/cuchaz/enigma/bytecode/translators/SourceFixVisitor.java
- src/main/java/cuchaz/enigma/command/MapSpecializedMethodsCommand.java
The `map-specialized-methods` command should be run by yarn on the built tiny files so that loom (and other remappers) can map them to the correct name. I'll make a yarn PR once this is merged.
> Correctly decompile bridges, and add command to add specialized methods to mappings

- src/main/java/cuchaz/enigma/gui/GuiController.java
Fixes #200.
`EntryReference.getNameableEntry()` specifically excludes constructors (and does nothing else), so I switched it to always use the entry field.
> Fix documenting constructors

- src/main/java/cuchaz/enigma/Main.java
- src/main/java/cuchaz/enigma/command/Command.java
- src/main/java/cuchaz/enigma/command/MapSpecializedMethodsCommand.java
- src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/EnigmaMappingsReader.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/EnigmaMappingsWriter.java
- src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
- src/main/java/cuchaz/enigma/utils/Utils.java
- src/main/resources/lang/en_us.json
Takes paths which are ZIP files as zipped mappings rather than trying to read it as a directory or mapping file. Passing in a `Path` directly from a ZIP file system will be read correctly where it is possible to do so.
> Add support for reading/writing zipped mappings

- src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
- src/main/java/cuchaz/enigma/source/procyon/index/TokenFactory.java
- Fixes crash with Procyon when a node has a bad region (accidentally removed the check in my last PR)
- Fixes CFR parameter indices being incorrect when method contains longs and doubles
- Fixes crash with CFR for classes with method references
> Fix CFR-related bugs

- src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
This appears to have been missed by an earlier commit that fixed this for the method below. It was biting me, so I fixed it.
> Fix division by zero

- src/main/java/cuchaz/enigma/translation/mapping/serde/TinyV2Reader.java
Currently, line breaks in Tiny v2 javadoc comments transform into `\\n` when converted to Enigma mappings, which will be `\n` in the comments in the decompiled code.
An `unescape` call fixes this since writing will escape it again (but only once instead of twice).
> Convert javadoc escape codes into raw characters when loading Tiny v2 mappings

- build.gradle
Fixes #224.
- All four jars are now published again: the one with no classifier, `-all`, `-lib` and `-sources`.
- `from components.java` includes the default jar and the dependencies in the POM.
> Fix POM issues

- build.gradle
- src/main/java/cuchaz/enigma/config/Config.java
- src/main/java/cuchaz/enigma/config/Themes.java
- src/main/java/cuchaz/enigma/gui/Gui.java
- src/main/java/cuchaz/enigma/gui/dialog/AboutDialog.java
- src/main/java/cuchaz/enigma/gui/dialog/CrashDialog.java
- src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
- src/main/java/cuchaz/enigma/gui/dialog/ProgressDialog.java
- src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
- src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
- src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java
- src/main/java/cuchaz/enigma/gui/panels/PanelIdentifier.java
- src/main/java/cuchaz/enigma/gui/util/ScaleChangeListener.java
- src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
- src/main/resources/lang/en_us.json
This is necessary because Swing doesn't scale correctly on HiDPI displays by default on Java 8, and at least on Linux only partly supports scaling since Java 9, and then only with an integer scale factor, so scaling by 1.5x is impossible.
> Add a configurable scale factor

- src/main/resources/lang/en_us.json
This changes `popup_menu.calls` to `Show Calls (All Implementations)`, to highlight the difference to `popup_menu.calls.specific` (`Show Calls (Specific)`) better.
> Highlight the difference between popup_menu.calls and popup_menu.calls.specific

- src/main/java/cuchaz/enigma/config/Config.java
This is what people have been getting, and it's apparently related to ScaleUtil.getDimension loading Config and Config calling ScaleUtil.getDimension
```
Exception in thread "main" java.lang.ExceptionInInitializerError
at cuchaz.enigma.utils.I18n.<clinit>(I18n.java:29)
at cuchaz.enigma.analysis.index.JarIndex.indexJar(JarIndex.java:64)
at cuchaz.enigma.analysis.ClassCache.index(ClassCache.java:124)
at cuchaz.enigma.Enigma.openJar(Enigma.java:49)
at cuchaz.enigma.command.Command.openProject(Command.java:37)
at cuchaz.enigma.command.DeobfuscateCommand.run(DeobfuscateCommand.java:30)
at cuchaz.enigma.CommandMain.main(CommandMain.java:43)
Caused by: java.lang.NullPointerException
at cuchaz.enigma.gui.util.ScaleUtil.getScaleFactor(ScaleUtil.java:25)
at …
```
> Fix circular class loading crash

- README.md
- build.gradle
- src/main/java/cuchaz/enigma/gui/ClassSelector.java
- src/main/java/cuchaz/enigma/gui/Gui.java
- src/main/java/cuchaz/enigma/gui/dialog/SearchDialog.java
- src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
- src/main/java/cuchaz/enigma/gui/panels/PanelEditor.java
- src/main/java/cuchaz/enigma/gui/util/AbstractListCellRenderer.java
- src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
- src/main/java/cuchaz/enigma/utils/search/SearchEntry.java
- src/main/java/cuchaz/enigma/utils/search/SearchUtil.java
- src/main/resources/lang/en_us.json
The search dialog has been completely broken for a while now so I rewrote the whole thing, UI included.
Internals changes: It now no longer uses an external library to do the search, but instead something that's as close to IntelliJ/Eclipse's search as I could get.
UI changes: The dialog is now persistent and will retain its last search term in the search box. The results list now includes the deobf name in addition to the obf name, and both names show the fully qualified name as a tooltip.
> Rewrite search dialog

- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
I tried to fix the name of the application, but failed to do so. this is the major improvement to mac os support.
> Use MacOS menu bar style

- enigma-server/src/main/java/cuchaz/enigma/network/packet/RenameC2SPacket.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
The entire entry setting API needs a more comprehensive overhaul since right now it's jank city, but this will do.
Closes #190.
> Fix javadoc loss when renaming entry

- enigma/src/main/java/cuchaz/enigma/bytecode/translators/TranslationSignatureVisitor.java
When there's 2 levels of inner classes, `visitInnerClassType` gets called twice... but it only ever calls `classStack.pop()`, never `push()`, so the stack is empty the next level of inner class.
This issue only occurs when exporting the server jar as source, since that includes all the server libraries, including classes like `Lit/unimi/dsi/fastutil/chars/Char2ObjectRBTreeMap<TV;>.Submap.SubmapIterator;`
Closes #119.
> Fix crash on remapping >1 level of nested class

- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
- enigma/src/main/java/cuchaz/enigma/source/DecompiledClassSource.java
It didn't do anything because the obfuscated entry and deobfuscated entry are never the same if the outer class has a deobfuscated name.
> Fix "Mark as Deobfuscated" menu entry not working

- build.gradle
- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
- enigma/src/main/java/cuchaz/enigma/analysis/EntryReference.java
- enigma/src/main/java/cuchaz/enigma/source/DecompiledClassSource.java
- enigma/src/main/java/cuchaz/enigma/translation/MappingTranslator.java
- enigma/src/main/java/cuchaz/enigma/translation/ProposingTranslator.java
- enigma/src/main/java/cuchaz/enigma/translation/Translatable.java
- enigma/src/main/java/cuchaz/enigma/translation/TranslateResult.java
- enigma/src/main/java/cuchaz/enigma/translation/Translator.java
- enigma/src/main/java/cuchaz/enigma/translation/VoidTranslator.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/MappingDelta.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/tree/EntryTree.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/Lambda.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/MethodDescriptor.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/Signature.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/TypeDescriptor.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassDefEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldDefEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/LocalVariableDefEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/LocalVariableEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodDefEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/MethodEntry.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ParentedEntry.java
See https://github.com/FabricMC/Enigma/commit/142b463faaad94f9fe8e33fe753ae5845b975ac6#r40131098
Previously, deobfuscate()/translate() and compare against obfuscated mapping was used to determine if a mapping was deobfuscated or not (for highlighting purposes). In #265 I changed this to use hasDeobfMapping because the previous equality check would never succeed for methods in classes with deobfuscated names, since it would compare against the whole thing, including the outer class name. Unfortunately the fix in #265 fails for overrides in subclasses because the mapping is in the superclass, and hasDeobfMapping doesn't check for that.
This adds extendedTranslate to Translatable, which, in addition to the resulting name, returns whether the returned name is deobfuscated, obfuscated or …
> Fix "Mark as Deobfuscated" menu entry not working... this time without breaking all the things hopefully

- enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
This adds support for Enigma source export functionality to choose how to handle errors. This is only a band-aid fix for the decompiler exceptions experienced in #279 and #283, but it will at least help to get partial source exports in the case of decompiler failures.
> Handle source export failures

- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
It looks like #289 forgot to import `PrintWriter` and `StringWriter` before using them here: https://github.com/FabricMC/Enigma/blob/467df0ee32517499a750a01aacfa724d7d5f2e36/enigma/src/main/java/cuchaz/enigma/EnigmaProject.java#L242-L243
Enigma builds again now
> Add missing PrintWriter and StringWriter imports

- enigma/src/main/java/cuchaz/enigma/translation/representation/TypeDescriptor.java
Causes type descriptor to not crash when getting type parameter called `T` in arrays (but not `U`, etc.) by extending the generics check to actually check for a `;` afterwards (afaik actual type parameter types are `TT;`, `TU;`, ..., which is where that T comes from)
Closes #182.
> Fix crash on remapping [T

- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
Currently, an array class such as `[LOuter$Inner;` would not get translated correctly because `new ClassEntry("[LOuter$Inner;")` calls `new ClassEntry("[LOuter", "Inner;")`, as if `Inner;` was an inner class of the parent class `[LOuter`. This PR fixes the parent class check to avoid this problem. (also see https://github.com/FabricMC/Enigma/pull/173)
> Fix array classes not being translated correctly

- enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/tinyv2/TinyV2Reader.java
- enigma/src/test/java/cuchaz/enigma/translation/mapping/TestReadWriteCycle.java
Found some issues with mapping formats while playing with Enigma lib
- Tiny V2 drops the last entries in the `holds` array (items in the queue were only 'baked' when the next entry showed up)
- Enigma File doesn't write anything at all (impossible stream filter `instanceof`)
I wrote a test to ensure all the formats (which have reader and writer) can do a read/write cycle without losing any mappings, which found an exception thrown on Enigma Zip format (Windows, OpenJDK 8)
> Mapping format fixes

- enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaSyntaxKit.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/config/Config.java
_I am old, I need big font :-|_
I didn't add a Dialog to set this because it seems like Swing has no default Font selection dialog.
So the only way to set it is to go to the config-file and enter it manually. For example: "Consolas-14".
> Allows setting the default editor font in the configuration file

- build.gradle
- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
- enigma/src/main/java/cuchaz/enigma/classhandle/ClassHandleProvider.java
- enigma/src/main/java/cuchaz/enigma/source/DecompiledClassSource.java
- enigma/src/main/java/cuchaz/enigma/source/Token.java
- enigma/src/main/java/cuchaz/enigma/source/TokenStore.java
In multiplayer, someone else renaming an entry would cause the cursor to be reset to the end of the file if there was no token selected. This fixes that by going through the length of all the tokens before the cursor and moving it by how much the length of the token has changed.
> Fix losing current cursor position when renaming entries

- enigma/src/main/java/cuchaz/enigma/config/ConfigPaths.java
`~/Library/Preferences` is for `.plist` files created by `.app` applications
> Set config path to Application Support on mac

- build.gradle
- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
It's possible to rename an entire package at once by pressing F2 in the deobf panel, but it resulted in invalid mapping files. This PR fixes that
Closes #304
> Fixed package renaming

- build.gradle
- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/elements/DeobfPanelPopupMenu.java
- enigma/src/main/resources/lang/en_us.json
- enigma/src/main/resources/lang/fr_fr.json
- Right clicking now select the closest path before opening the popup menu (instead of opening it for any previously selected path)
- Replaced the rename item with a rename package and a rename class items
- "Rename Package" rename the parent package if path is a class, or the path if it's already a package
- "Rename Class" rename the path only if it's a class, otherwise the item is disabled
> Improvements to deobf panel popup menu

- enigma-cli/src/main/java/cuchaz/enigma/command/DecompileCommand.java
- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
As explained in PR #289, the decompilers may fail decompiling some vanilla Minecraft classes. Although it is my opinion that these errors should be fixed in the decompilers themselves, currently they render the decompile CLI command useless, as no output is produced whatsoever.
The PR that was mentioned previously addressed this situation for the GUI part of Enigma, but not for the CLI commands, which were left untouched.
These changes modify the decompiler error strategy used by the aforementioned CLI command to trace the errors, but continue decompiling classes, so at least a partial output is generated. This way users will be happy that the Enigma decompile command works, and developers will still be motivated to fix the underlying issues.
> Do not abort decompile command on decompiler errors

- enigma/src/main/java/cuchaz/enigma/classhandle/ClassHandleProvider.java
When saving javadocs on inner classes, they were not displayed on the editor panel without closing and reopening the outer class.
This PR fixes that by invalidating javadocs on the outermost parent class in addition to the class where javadocs are added.
Closes #276
> Fix inner classes' javadocs not invalidated properly

- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
Fixes a bug where the structure panel would not update the shown class when the user switches to a previously opened tab.
The cause was that the `showStructure` call was inside a `computeIfAbsent`, so it wasn't called when the editor already existed. I moved the call to the following `if (editorPanel != null)` block instead.
> Fix the structure panel not updating if switching to an existing tab

- enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
- enigma/src/main/java/cuchaz/enigma/analysis/EntryReference.java
- enigma/src/main/java/cuchaz/enigma/source/SourceIndex.java
The problem is that "open declaration" does not open declaration; it only goes to the topmost token in the class where the declaration is. Edited entry reference to add "declaration reference" for navigation.
Example: Look at the `setPosition` call in `Entity`'s constructor. When you navigate you will go back to the constructor because it is the first occurrence of `setPosition`.
This bug may have been overlooked because for fields and classes, their definitions usually are lucky enough to be the first references in their files.
Also make navigating to a reference open the outermost than the inner class. For example, look at the implementations of `EntityData`. Now you will not go to `PassiveEntity$PassiveData` but will just go to `PassiveEntity`.
Imo this bug is significant and affects …
> Fixes open declaration not opening declaration

- enigma/build.gradle
- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
- enigma/src/main/java/cuchaz/enigma/classhandle/ClassHandleProvider.java
- enigma/src/main/java/cuchaz/enigma/source/Decompiler.java
- enigma/src/main/java/cuchaz/enigma/source/Source.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/CfrDecompiler.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/CfrSource.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
- enigma/src/main/java/cuchaz/enigma/source/procyon/ProcyonDecompiler.java
- enigma/src/main/java/cuchaz/enigma/source/procyon/ProcyonSource.java
Now it can display javadoc, remove imports, highlight local variables
Depends on FabricMC/cfr#2, so opened as a draft
Changes required in yarn is minimal. It simply needs an enigma update and can immediately start enjoying these improvements!
Effect: 
Look at this living entity class that procyon can never decompile. Now it doesn't have imports and shows javadocs!
> Make cfr much easier to use

- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/elements/EditorTabPopupMenu.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/StructurePanel.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/CallsTreeCellRenderer.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/ImplementationsTreeCellRenderer.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/InheritanceTreeCellRenderer.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/renderer/MessageListCellRenderer.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
- enigma/src/main/java/cuchaz/enigma/analysis/ClassInheritanceTreeNode.java
- enigma/src/main/java/cuchaz/enigma/analysis/MethodInheritanceTreeNode.java
- enigma/src/main/java/cuchaz/enigma/analysis/ReferenceTreeNode.java
- enigma/src/main/java/cuchaz/enigma/analysis/StructureTreeNode.java
This PR makes the inheritance, implementations and calls trees use icons for classes/methods/fields references.
Also, fixes the editor tab popup menu not being retranslated when changing the language.
EDIT: fixes #357 (didn't see the issue before)
> Icons everywhere

- README.md
- enigma-swing/build.gradle
- enigma-swing/src/main/java/cuchaz/enigma/gui/EnigmaSyntaxKit.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/config/LookAndFeel.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
- enigma/src/main/resources/lang/en_us.json
Fixes #355.
- Replaces the Darcula look and feel with [FlatLaf](https://github.com/JFormDesigner/FlatLaf)'s dark colour scheme.
- FlatLaf does not have the same rendering bugs with CJK characters (at least on Windows 10).
- FlatLaf is also under Apache 2.0, so we can use it as a drop-in replacement. It also looks almost identical to Darcula with the dark theme as they have the same colours and overall style.
- Replaces Metal with FlatLaf Light as the default look and feel. Metal is provided as a new, separate theme option.
- FlatLaf Light looks a lot better than Metal (especially as a default theme for a modern application), so I decided to use it as the default. Metal can still be used with the other options.
- The javadoc editor dialog's text box now uses the editor font for …
> Migrate to FlatLaf

- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
Resolves #353 
The issue here lies in that this changes the behaviour of the code by quite a bit, so alternatively the irrelevant javax check could be dropped, which would optimize the code only slightly
> Less strict JRE check

- enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
- enigma/src/main/java/cuchaz/enigma/bytecode/translators/TranslationClassVisitor.java
- enigma/src/main/java/cuchaz/enigma/bytecode/translators/TranslationRecordComponentVisitor.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/AccessFlags.java
- enigma/src/main/java/cuchaz/enigma/utils/validation/Message.java
- enigma/src/main/resources/lang/en_us.json
- Full record support include javadoc support
- The generated method getter will also get a mapping of the same name to the field.
- Also fixes a bug where engima would open off the screen.
- This assumes that the fields, methods and components will all have the same name when obfuscated, im unsure if this is always the case. If not some logic will be needed to tie them back togeather.
- When exporting a jar it is currenly failing to remap one of the records' bsmArgs in the generated `toString` method.
I'm more than a little rusty on Engima so please don't hesistate to point out any issues 👍
> Record support

- enigma/build.gradle
- gradle/wrapper/gradle-wrapper.properties
fabric cfr 0.03 was released a while ago but not used. It fixes a few annoying problems with the current fabric cfr.
@sfPlayer1 Mind check this and publish a new enigma build and bump enigma in yarn? Now seems procyon doesn't work quite well with 16 for me, cfr may be a viable solution.
> Bump cfr and gradle wrapper

- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
A number of users have reported crashes with awt's FileDialog when using Java 16. Apparenly Java 17 contains a fix for this. This is a quick PR to use JFileChooser everywhere, its not native but works.
An alternative would be use LWJGL's native bindings to https://github.com/mlabbe/nativefiledialog but that seems over the top when this is the quick and simple solution.
> Use JFileChooser for all open/save operations

- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/DeobfPanel.java
- enigma/src/main/resources/lang/en_us.json
Parchment uses a jar with already remapped classes, but Enigma puts them into panel with obf classes which sorts classes by length. This option puts all classes into the deobf panel, and completely hides the obf panel.
> Add --single-class-tree argument that puts all classes into deobf panel & hides obf panel

- enigma-swing/src/main/java/cuchaz/enigma/gui/util/GuiUtil.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/EntryRemapper.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/AccessFlags.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassDefEntry.java
- Improve record class detection, the access flag is only added by ASM when it finds a record atribute on the class, we now use the super class.
- Also generate a method mapping for the record entry, does not support the case of the method having a diffrent name from the field. This needs looking at, but is not an issue for yarn as it will be ran ontop of an intermediary named jar.
- If there is a record component this is stilled remapped via the field mapping.
> Record handling improvements

- enigma-swing/src/main/resources/icons/annotation.svg
- enigma-swing/src/main/resources/icons/constructor.svg
- enigma-swing/src/main/resources/icons/record.svg
Right now the Annotation icon is the same colour as Interface, Record is the same colour as Class, and Constructor is the same colour as Method
This PR gives them each unique colours. Why not?
An example of them in-program: https://imgur.com/a/NmE2HJ5
> Give Annotation, Record, and Constructor icons their own colours

- enigma-swing/src/main/resources/icons/constructor.svg
Successor to #436 
As they're both 'C's, having them both be different reds was... less than ideal.
Now Constructor is Dark Blue, which also emphasizes its relationship to Method which is light blue
> Change Constructor icon colour to be more distinct from Class

- enigma/src/main/java/cuchaz/enigma/source/cfr/CfrDecompiler.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/CfrSource.java
This removes all caching/sharing around CFR's `DCCommonState` this has a number of benefits:
- Exporting sources works great with `-Xmx2G` before `-Xmx32G` was needed!
- Exporting sources is now parallel as the none thread safe state is no longer shared between classes.
- Decompiles may be slightly slower, in my testing I cannot notice any difference (Please let me know if you do!)
- When exporting all sources with a small max heap size the GC will thash quite a bit, not a major issue IMO.
> Fix memory leak with CFR decompiler interface.

- enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
Partly taken from https://github.com/QuiltMC/enigma/commit/28de6ea4874ba77fcbea50919f7897ee2ba9bd7c.
See:
- https://docs.oracle.com/javase/8/docs/technotes/guides/2d/flags.html#aaFonts
- https://wiki.archlinux.org/title/Java_Runtime_Environment_fonts#Overriding_the_automatically_picked_up_settings
- https://github.com/JFormDesigner/FlatLaf/issues/307#issuecomment-823554775.
> Provide fallback anti-aliasing for DEs the JRE doesn't recognize

- enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
Taken from https://github.com/QuiltMC/enigma/commit/226d5b03b4145b8675b1b5dbffc153eb88e97db1. Partly supersedes #470.
> As of now, references to mapped constructors appear as `ExampleClass::ExampleClass` instead of `ExampleClass::new`. Obfuscated classes appear correctly as `a::new`.
> Fix constructor references being remapped

- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
- enigma/src/main/java/cuchaz/enigma/source/cfr/EnigmaDumper.java
Taken from https://github.com/QuiltMC/enigma/commit/fe9c232b65beb7e27964a92c1dc55509de4da127, https://github.com/QuiltMC/enigma/commit/1d8067cf6526223a9efa74e83d22addd529a4289 ~~and https://github.com/QuiltMC/enigma/commit/226d5b03b4145b8675b1b5dbffc153eb88e97db1~~.
Fixes #330.
> Make enum methods `values` and `valueOf` unmappable

- enigma/src/main/java/cuchaz/enigma/source/cfr/CfrDecompiler.java
#497 
The characters in the token were escaped in the source, but I fixed it by setting convertUTF of EnigmaDumper to false.
token:
source:
I set convertUTF in EnigmaDumper to false to fix it.
token:
source:
> fix UTF8 character bug

- enigma-swing/src/main/java/cuchaz/enigma/gui/stats/StatsGenerator.java
[26ba5a5](https://github.com/FabricMC/Enigma/commit/26ba5a59976a8b4a5e9d71d52f5a13a2aa2882de) originally fixed this issue (#503) but the exceptions persists when the package name is null. This PR attempts to fix that.
> Fix NullPointerException in mapping stats when package name is null

- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/FieldEntry.java
It has been accidentally removed in #475. Seems like I was a bit too careless when copying over commits from team pineapple.
> Fix `canConflictWith` check for fields

- enigma-swing/src/main/java/cuchaz/enigma/gui/NestedPackages.java
Fixes #471. The current code's issue is that `entry.getPackageName()` here: https://github.com/FabricMC/Enigma/blob/08d9e28bdc00ac7846e551e5eef7ebf9ffc63b74/enigma-swing/src/main/java/cuchaz/enigma/gui/NestedPackages.java#L92-L93
already returns the new package name, not the old one, which is required. We can circumvent this by simply using the UI node's parent instead, which still points to the old entry.
> Fix ghost entries caused by packages becoming empty

- enigma-swing/src/main/java/cuchaz/enigma/gui/elements/EditorTabPopupMenu.java
This PR makes the `CTRL` + `SHIFT` + `4` key combo close all editor tabs, similar to how browsers handle `CTRL` + `W` and `CTRL` + `SHIFT` + `W`.
> Allow using ctrl-shift-4 to close all open tabs

- enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
Fixes  #523.
```diff
- try (FileWriter w = new FileWriter(statsFile)) {
+ try (FileWriter w = new FileWriter(statsFile, StandardCharsets.UTF_8)) {
```
before:
after:
> Fix StatsGenerator encoding

- enigma/src/main/java/cuchaz/enigma/analysis/index/IndexReferenceVisitor.java
- enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndex.java
- enigma/src/main/java/cuchaz/enigma/analysis/index/JarIndexer.java
- enigma/src/main/java/cuchaz/enigma/analysis/index/ReferenceIndex.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/entry/ClassEntry.java
Until now, Enigma only indexed class references through constructor methods. With this PR, it now indexes class references in 3 more ways:
- When used in `instanceof`
- When used in a cast
- When the class itself is called (`MyClass.class`), which fixes #26
> Index more class references

- enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
Fixes #200, which was reintroduced at some point.
The fix is modelled after
1. My original PR #201 (using `entry` instead of `getNameableEntry()`, since the latter specifically only excludes constructors)
2. The CFR bridge code's `EnigmaDumper`, which always uses `EntryMapping` to access javadoc
> Fix documenting constructors (again)

- enigma-swing/src/main/java/cuchaz/enigma/gui/config/UiConfig.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/highlight/BoxHighlightPainter.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/highlight/SelectionHighlightPainter.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
- The editor font actually scales now. It didn't before because of multiple reasons:
- `editor.setFont` was called too early. In this state, the editor doesn't have a font applied, so the system default (non-monospaced!) is returned.
- This didn't matter though, since `editor.setContentType("text/enigma-sources")` overwrote it anyway with the `DefaultFont` property defined in `EnigmaSyntaxKit` (making the `DEFAULT_FONT` reflection hack redundant, no idea why that existed).
- `DefaultFont` is usually set to `UiConfig.getFallbackEditorFont()`, which intends to scale the default monospace font to the current DPI settings.
- This didn't work either though, as `BasicTweaker#modifyFont` only scales `UIResource`s, which `Font` is not a subclass of.
- Highlight boxes are now scaled correctly too.
> Fix editor scaling

- enigma-swing/src/main/java/cuchaz/enigma/gui/panels/EditorPanel.java
We don't care about the undo/redo history of the syntax pane, any change history would be stored separately
> Clear undo history when updating editor text.

- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
error example: 
java.nio.file.NoSuchFileException: /Users/taewonkim/Develop/Java/Minecraft/net/minecraft/client/gui/chat/ChatListener.java
at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3008)
at java.base/java.nio.file.Files.newBufferedWriter(Files.java:3056)
at …
> fix NoSuchFileException when exporting sources (not jar)

- enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
> Invert Mapping-IO Proguard mappings to mirror legacy behavior

- enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
- enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/enigma/EnigmaMappingsWriter.java
MIO's `EnigmaDirWriter` doesn't support writing deltas only, so it deletes the parent directory and rewrites all the mapping files on every save, which is very slow. This PR delegates writes to Enigma's old dir writer, but using MIO's `EnigmaFileWriter` under the hood.
Long-term we need to add native diff handling to MIO.
> Add temporary bodge to MIO Enigma dir writer to support deltas

- build.gradle
- enigma/src/main/java/cuchaz/enigma/translation/mapping/serde/MappingFormat.java
- enigma/src/main/resources/lang/en_us.json
Adds support for IntelliJ migration maps.
> Update to Mapping-IO 0.7

- enigma-server/src/main/java/cuchaz/enigma/network/DedicatedEnigmaServer.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/Gui.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/GuiController.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/elements/MenuBar.java
- enigma/src/main/java/cuchaz/enigma/Enigma.java
- enigma/src/main/java/cuchaz/enigma/EnigmaProject.java
- enigma/src/main/java/cuchaz/enigma/utils/Utils.java
This is needed for FabricMC/fabric-loom#1354.
Note for collab sessions: multiple jars should specified in the enigma-swing CLI to set the exact order. The Swing file picker always chooses them in alphabetical order, which may not match what the server has. (Alternatively, the server should specify them in alphabetical order 🙂)
TODO:
> Support multiple input jars

- enigma-cli/src/main/java/cuchaz/enigma/command/Command.java
- enigma-cli/src/main/java/cuchaz/enigma/command/MappingCommandsUtil.java
- enigma-server/src/main/java/cuchaz/enigma/network/DedicatedEnigmaServer.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/Main.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/config/legacy/Config.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/dialog/JavadocDialog.java
- enigma-swing/src/main/java/cuchaz/enigma/gui/util/ScaleUtil.java
- enigma/src/main/java/cuchaz/enigma/analysis/StructureTreeNode.java
- enigma/src/main/java/cuchaz/enigma/translation/representation/AccessFlags.java
`toUpperCase` and `toLowerCase` specify `Locale.ROOT` everywhere now. I think there were existing strings that would cause issues on Turkish computers in `ScaleUtil` and the `.zip` extension checks.
> Fix locale-dependent letter case conversions
